language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - npm run build

after_script:
  - cd build
  - git init
  - git remote add origin "https://${GH_TOKEN}@${GH_REF}"
  - git config user.name "${GH_USER}"
  - git config user.email "${GH_EMAIL}"
  - git add .
  - git commit -m "CI BUILD"
  - git pull origin master
  - git push origin master

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/hello-nav/hello-nav.github.io.git