language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - npm run build

after_script:
  - git clone "https://${GH_TOKEN}@${GH_REF}" repo
  - cd repo
  - rm -rf ./*
  - cp -r ../build/* ./
  - git config user.name "${GH_USER}"
  - git config user.email "${GH_EMAIL}"
  - git add .
  - git commit -m "CI BUILD"
  - git push origin master

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/hello-nav/hello-nav.github.io.git